---
- name: Get latest version
  shell: curl -s https://github.com/hashicorp/terraform/releases/latest | cut -f2 -d'v' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true
  args:
    warn: off

- name: "Latest version of terraform:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of terraform"
  set_fact:
    terraform_version: "{{ version.stdout }}"
