---
- name: Get latest version of stern
  shell: curl -s https://github.com/wercker/stern/releases/latest | cut -f8 -d'/' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true
  args:
    warn: off

- name: "Latest version of stern:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of stern"
  set_fact:
    stern_version: "{{ version.stdout }}"
