---
- name: Add Docker-CE rpm repo gpg key
  rpm_key:
    state: present
    key: https://download.docker.com/linux/fedora/gpg

- name: Add Docker-CE repository to yum/dnf
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Remove preinstalled docker
  dnf:
    name: "{{ pkgs }}"
    state: absent
  vars:
    pkgs:
      - docker
      - docker-io
      - docker-common

- name: Docker install
  dnf:
    name: "{{ pkgs }}"
    state: latest
  vars:
    pkgs:
      - docker-ce
      - docker-ce-cli
      - containerd.io
