---
- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
    state: started
  when: docker_tests_flag is not defined

- name: Add the user to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes

### add systemd.unified_cgroup_hierarchy=0 to grub cmdline
