---
- name: Update all clevo vms and host
  hosts: mikeeClevo
  become: true
  tasks:
    - name: Install dnf-utils
      ansible.builtin.dnf:
        name: "dnf-utils"
        state: present

    - name: Check if reboot required
      shell: |
        needs-restarting -r
      register: reboot_required

    - name: Reboot if required
      reboot:
      when:
        - reboot_required.rc != 0
